apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: loadtxqg1486-tenant-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: loadtxqg1486-tenant-component
    app.kubernetes.io/part-of: loadtxqg1486-tenant-app
  name: loadtxqg1486-tenant-component
  namespace: loadtxqg1486-tenant
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: loadtxqg1486-tenant-component
    weight: null
status: {}
